In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import m2cgen as m2c
import numpy as np
from collections import deque

In [2]:
df=pd.read_csv('C:/Users/bogda/gazpromhack/data/matan25.csv', encoding='UTF-8', sep=',')
df.head()

,Unnamed: 0,TimeStamp,Температура масла в магистрали общей откачки (поз. Тм),Температура слива масла из опоры турбины (поз. Т606),Температура масла на входе в двигатель за фильтром (поз. Т607),Температура топливного газа перед СК (перед расходомерным устройством) (поз. Ттг),Давление масла в нагнетающей магистрали двигателя (после фильтра) (поз. Pм),Давление масла в магистрали общей откачки (поз. Р615),Давление за ОК Pk1,Давление за ОК Pk2,...,Частота вращения РНД (Расчетная),Частота вращения РВД (Расчетная),Частота вращения РСТ (Расчетная),Температура воздуха на входе в газогенератор (Расчетная),Давление воздуха за компрессором (Расчетная),Частота вращения РНД приведенная,Частота вращения РВД приведенная,Температура газов за ТНД максимальная (Расчетная),Положение лопаток НА КВД. (поз. A2),Положение КПВ (поз. A3)
0,0,1,21.548,28.16,0.22,95.629154,551.636308,84.595686,244.713,257.59,...,4052.99,9784.279038,1490.427,0.22,250.959,4063.420835,9722.291,0.22,764.719204,8.072
1,1,24,21.548,28.16,0.22,254.455795,166.136415,448.827560,244.713,257.59,...,4052.99,9784.279038,1490.427,0.22,250.959,3974.665128,9722.291,0.22,764.719204,8.072
2,2,46,21.548,28.16,0.22,0.220000,489.148753,72.215314,244.713,257.59,...,4052.99,9784.279038,1490.427,0.22,250.959,3942.034270,9722.291,0.22,764.719204,8.072
3,3,68,21.548,28.16,0.22,133.596260,263.609514,376.072851,244.713,257.59,...,4052.99,9784.279038,1490.427,0.22,250.959,4055.233266,9722.291,0.22,764.719204,8.072
4,4,91,21.548,28.16,0.22,88.929535,92.540477,46.708708,244.713,257.59,...,4052.99,9784.279038,1490.427,0.22,250.959,4293.601648,9722.291,0.22,764.719204,8.072

In [26]:
df=pd.read_csv('C:/Users/bogda/gazpromhack/data/1.csv', encoding='cp1251', sep=';')
df.head()

,TimeStamp,Температура масла в магистрали общей откачки (поз. Тм),Температура слива масла из опоры турбины (поз. Т606),Температура масла на входе в двигатель за фильтром (поз. Т607),Температура топливного газа перед СК (перед расходомерным устройством) (поз. Ттг),Давление масла в нагнетающей магистрали двигателя (после фильтра) (поз. Pм),Давление масла в магистрали общей откачки (поз. Р615),Давление за ОК Pk1,Давление за ОК Pk2,Давление топливного газа перед дозаторами (поз. Pтг1.1),...,Частота вращения РНД (Расчетная),Частота вращения РВД (Расчетная),Частота вращения РСТ (Расчетная),Температура воздуха на входе в газогенератор (Расчетная),Давление воздуха за компрессором (Расчетная),Частота вращения РНД приведенная,Частота вращения РВД приведенная,Температура газов за ТНД максимальная (Расчетная),Положение лопаток НА КВД. (поз. A2),Положение КПВ (поз. A3)
0,12:10:00.001,21.548,28.16,24.361,8.762,302.095,198.239,244.713,257.590,2917.776,...,4052.990,9564.946,1490.427,5.601,250.959,4119.418,9722.291,439.119,16.139,8.072
1,12:10:00.024,21.548,28.16,24.361,8.762,302.095,198.239,244.713,257.590,2917.776,...,4053.209,9565.001,1490.403,5.601,251.152,4119.683,9722.339,439.119,16.139,8.072
2,12:10:00.046,21.548,28.16,24.361,8.762,302.559,198.220,243.865,258.663,2916.046,...,4053.209,9565.001,1490.403,5.601,251.152,4119.905,9722.395,439.119,15.876,7.931
3,12:10:00.068,21.548,28.16,24.361,8.762,302.559,198.220,243.865,258.663,2916.046,...,4053.079,9564.868,1490.337,5.601,251.264,4119.905,9722.395,439.107,15.876,7.931
4,12:10:00.091,21.548,28.23,24.361,8.762,302.262,197.553,243.865,257.820,2915.057,...,4053.079,9564.868,1490.337,5.601,251.264,4119.773,9722.260,439.107,15.758,7.931

In [ ]:
df=pd.read_csv('C:/Users/bogda/gazpromhack/data/matan25.csv', encoding='UTF-8', sep=',')
df.head()

In [ ]:
# class TrendingCusumDetector:
#     def __init__(self, target_slope, sigma_slope, h_factor=5):
#         self.target_slope = target_slope
#         self.K = 0.5 * sigma_slope
#         self.H = h_factor * sigma_slope
        
#         self.s_high = 0.0
#         self.s_low = 0.0
#         self.last_val = None

#     def update(self, val):
#         if self.last_val is None:
#             self.last_val = val
#             return False, 0, 0
        
#         current_slope = val - self.last_val
#         self.last_val = val
        
#         diff = current_slope - self.target_slope
        
#         self.s_high = max(0, self.s_high + diff - self.K)
#         self.s_low = max(0, self.s_low - diff - self.K)
        
#         alarm = (self.s_high > self.H) or (self.s_low > self.H)
#         return alarm, self.s_high, self.s_low

In [13]:
class KalmanFilter2DWithPersistence:
    def __init__(self, q=1e-4, r=1e-2, persistence=5):
        self.x = np.array([0.0, 0.0])
        self.f = np.array([[1.0, 1.0], [0.0, 1.0]])
        self.h = np.array([[1.0, 0.0]])
        self.p = np.eye(2) * 1.0
        self.q = np.eye(2) * q
        self.r = np.array([[r]])
        self.is_initialized = False
        
        # Параметры подтверждения
        self.persistence_limit = persistence
        self.anomaly_counter = 0

    def update(self, measurement, threshold):
        if not self.is_initialized:
            self.x[0] = measurement
            self.is_initialized = True
            return False, measurement, 0.0

        # Предсказание и коррекция Калмана
        x_pred = self.f @ self.x
        self.p = self.f @ self.p @ self.f.T + self.q
        innovation = measurement - x_pred[0]
        s = self.h @ self.p @ self.h.T + self.r
        k = self.p @ self.h.T @ np.linalg.inv(s)
        self.x = x_pred + k.flatten() * innovation
        self.p = (np.eye(2) - k @ self.h) @ self.p

        error = abs(innovation)
        
        # --- ЛОГИКА ПОДТВЕРЖДЕНИЯ ---
        if error > threshold:
            self.anomaly_counter += 1
        else:
            # Сбрасываем или уменьшаем счетчик, если сигнал в норме
            self.anomaly_counter = 0 
            
        # Тревога только если аномалия длится долго
        alarm = self.anomaly_counter >= self.persistence_limit
        
        return alarm, self.x[0], error

In [12]:
class KalmanFilter2D:
    def __init__(self, q=1e-4, r=1e-2):
        # Состояние: [значение, скорость]
        self.x = np.array([0.0, 0.0])
        
        # Матрица перехода (предсказываем: x_new = x + velocity)
        self.f = np.array([[1.0, 1.0],
                           [0.0, 1.0]])
        
        # Матрица измерения (мы видим только значение)
        self.h = np.array([[1.0, 0.0]])
        
        # Ковариация ошибки
        self.p = np.eye(2) * 1.0
        
        # Шумы
        self.q = np.eye(2) * q
        self.r = np.array([[r]])
        
        self.is_initialized = False

    def update(self, measurement):
        if not self.is_initialized:
            self.x[0] = measurement
            self.is_initialized = True
            return 0.0, self.x[0]

        # 1. Prediction (Предсказание)
        x_pred = self.f @ self.x
        self.p = self.f @ self.p @ self.f.T + self.q

        # 2. Innovation (Ошибка прогноза)
        # Насколько реальность (measurement) отличается от прогноза (x_pred[0])
        innovation = measurement - x_pred[0]

        # 3. Update (Коррекция)
        s = self.h @ self.p @ self.h.T + self.r
        k = self.p @ self.h.T @ np.linalg.inv(s)
        
        self.x = x_pred + k.flatten() * innovation
        self.p = (np.eye(2) - k @ self.h) @ self.p

        return innovation, self.x[0]

In [28]:
class EnsembleDetector:
    def __init__(self, slew_threshold, std_threshold, kalman_threshold, 
                 window_size=20, persistence=2, k_q_val=0.0001, k_r_val=0.1):
        # 1. Параметры Slew Rate
        self.slew_threshold = slew_threshold
        self.last_val = None
        
        # 2. Параметры Moving StdDev
        self.window_size = int(window_size) # Гарантируем int
        self.buffer = np.zeros(self.window_size)
        self.buf_idx = 0
        self.count = 0
        self.std_threshold = std_threshold
        
        # 3. Параметры Kalman
        self.k_x = 0.0      
        self.k_v = 0.0      
        self.k_p = np.eye(2) 
        self.k_q = np.eye(2) * k_q_val 
        self.k_r = k_r_val      
        self.kalman_threshold = kalman_threshold
        self.is_kf_init = False

        # 4. Логика подтверждения
        self.persistence_limit = persistence
        self.suspect_counter = 0

    def _kalman_step(self, val):
        if not self.is_kf_init:
            self.k_x = val
            self.is_kf_init = True
            return 0.0
        
        x_pred = self.k_x + self.k_v
        v_pred = self.k_v
        self.k_p[0,0] += self.k_p[1,1] + self.k_q[0,0]
        
        innovation = val - x_pred
        s = self.k_p[0,0] + self.k_r
        k_gain_x = self.k_p[0,0] / s
        k_gain_v = self.k_p[0,1] / s

        self.k_x = x_pred + k_gain_x * innovation
        self.k_v = v_pred + k_gain_v * innovation
        self.k_p[0,0] *= (1 - k_gain_x)
        
        return abs(innovation)

    def update(self, val):
        # 1. Slew Rate
        slew_err = abs(val - self.last_val) if self.last_val is not None else 0
        slew_alarm = slew_err > self.slew_threshold
        
        # 2. Moving StdDev
        self.buffer[self.buf_idx] = val
        self.buf_idx = (self.buf_idx + 1) % self.window_size
        self.count = min(self.count + 1, self.window_size)
        current_std = np.std(self.buffer[:self.count]) if self.count > 1 else 0
        std_alarm = current_std > self.std_threshold
        
        # 3. Kalman
        kalman_err = self._kalman_step(val)
        kalman_alarm = kalman_err > self.kalman_threshold

        # ЛОГИКА: Резкий скачок — это когда ХОТЯ БЫ ОДИН метод сработал
        if slew_alarm or kalman_alarm or std_alarm:
            self.suspect_counter += 1
        else:
            self.suspect_counter = 0 # Сбрасываем сразу, если это не аномалия

        # Для скачков persistence должен быть маленьким (1-3)
        final_alarm = (self.suspect_counter >= 1) and (self.suspect_counter <= self.persistence_limit)
        
        self.last_val = val
        return {
            'val': val,
            'slew_err': slew_err,
            'std_val': current_std,
            'kalman_err': kalman_err,
            'alarm': final_alarm
        }

In [24]:
class RobustStateDetector:
    def __init__(self, window_size=30, threshold_factor=3.0, max_spike_duration=4, min_threshold=0.5):
        self.window_size = window_size
        self.factor = threshold_factor
        
        # Максимальная длительность скачка. Если значение отклонено дольше 
        # этого времени, мы считаем, что это не скачок, а переход в новый режим.
        self.max_spike_duration = max_spike_duration
        self.min_threshold = min_threshold
        
        self.buffer = deque(maxlen=window_size)
        self.anomaly_counter = 0
        
    def update(self, val):
        self.buffer.append(val)
        
        if len(self.buffer) < self.window_size:
            return False, 0.0, 0.0
        
        arr = np.array(self.buffer)
        median = np.median(arr)
        
        # Считаем MAD. Добавляем мизерное число 1e-6, чтобы не делить на ноль, 
        # если все значения в окне одинаковые
        mad = np.median(np.abs(arr - median))
        sigma = 1.4826 * mad
        
        # Рассчитываем порог
        actual_threshold = max(self.factor * sigma, self.min_threshold)
        
        deviation = abs(val - median)
        is_outlier = deviation > actual_threshold
        
        if is_outlier:
            self.anomaly_counter += 1
        else:
            self.anomaly_counter = 0
            
        # ЛОГИКА ДЛЯ СКАНДАЛОВ (SPIKES):
        # 1. Мы даем тревогу СРАЗУ (как только нашли отклонение)
        # 2. НО, если отклонение длится дольше max_spike_duration, мы ГАСИМ тревогу.
        # Это значит, что график просто поднялся и остался там (ступенька).
        
        is_alarm = False
        if is_outlier and self.anomaly_counter <= self.max_spike_duration:
            is_alarm = True
            
        return is_alarm, deviation, actual_threshold

In [4]:
class TrendingCusumDetectorFiltered:
    def __init__(self, target_slope, sigma_slope, h_factor=50, k_factor=2.0, alpha=0.2):
        self.target_slope = target_slope
        
        # Увеличиваем мертвую зону (k_factor с 0.5 до 2.0)
        # Теперь отклонение должно быть значительным, чтобы начать копиться
        self.K = k_factor * sigma_slope 
        
        # Увеличиваем порог (h_factor с 10 до 50-100)
        self.H = h_factor * sigma_slope
        
        self.s_high = 0.0
        self.s_low = 0.0
        
        self.last_val = None
        self.smoothed_val = None
        self.alpha = alpha
        
        # Коэффициент "утечки" (чтобы аларм не висел вечно)
        self.decay = 0.99 

    def update(self, val):
        if self.smoothed_val is None:
            self.smoothed_val = val
            self.last_val = val
            return False, 0, 0
        
        # Сглаживание
        self.smoothed_val = self.alpha * val + (1 - self.alpha) * self.smoothed_val
        current_slope = self.smoothed_val - self.last_val
        self.last_val = self.smoothed_val
        
        diff = current_slope - self.target_slope
        
        # Накопление с "утечкой" и мертвой зоной
        self.s_high = max(0, (self.s_high + diff - self.K) * self.decay)
        self.s_low = max(0, (self.s_low - diff - self.K) * self.decay)
        
        alarm = (self.s_high > self.H) or (self.s_low > self.H)
        return alarm, self.s_high, self.s_low

In [4]:
def add_features(df, column_name, window=50):
    df['mean'] = df[column_name].rolling(window=window).mean()
    df['std'] = df[column_name].rolling(window=window).std()
    df['slope'] = df[column_name].diff()
    df = df.fillna(0)
    return df

In [5]:
def difference(df, column):
    data=df[column]
    results=[]
    results.append({"diff": 0})
    for i in range(1,len(data)):
        diff=data[i]-data[i-1]
        results.append({"diff": diff})
    return pd.DataFrame(results)

In [6]:
def accelerate(df, column):
    data=df[column]
    results=[]
    for i in range(2):
        results.append({"acc": 0})
    for i in range(2,len(data)):
        acc=(data[i]-data[i-1])-(data[i-1]-data[i-2])
        results.append({"acc": acc})
    return pd.DataFrame(results)

In [6]:
def analyze_sensor_data(df, sensor_column, alpha=0.1):
    data = df[sensor_column].values
    
    # Увеличиваем окно обучения до 500 точек, чтобы лучше понять среднюю скорость
    train_idx = min(500, len(data))
    training_data = data[:train_idx]
    
    # Считаем параметры на сглаженных данных
    smoothed_train = []
    curr = training_data[0]
    for v in training_data:
        curr = alpha * v + (1 - alpha) * curr
        smoothed_train.append(curr)
    
    deltas = np.diff(smoothed_train)
    target_slope = np.mean(deltas)
    sigma_slope = np.std(deltas)
    
    if sigma_slope < 1e-6: sigma_slope = 1e-6

    # Настройки для уменьшения ложных срабатываний:
    # h_factor=100 (высокий порог), k_factor=5.0 (большая мертвая зона)
    detector = TrendingCusumDetectorFiltered(
        target_slope=target_slope, 
        sigma_slope=sigma_slope, 
        h_factor=100, 
        k_factor=5.0, 
        alpha=alpha
    )

    results = []
    for val in data:
        alarm, sh, sl = detector.update(val)
        results.append({'val': val, 's_high': sh, 's_low': sl, 'alarm': alarm})
    
    return pd.DataFrame(results)

d=analyze_sensor_data(df, 'Температура масла в магистрали общей откачки (поз. Тм)')
d['alarm'].value_counts()
# n=-1
# l=0
# for i in d['alarm']:
#     n+=1
#     if i == False:
#         l+=1
#         print(n)
#         if l == 800:
#             break

alarm
True     11488
False     1171
Name: count, dtype: int64

In [14]:
def analyze_sensor_final(df, column_name, q=1e-4, r=1e-1, persistence=5):
    data = df[column_name].values
    
    # 1. Первый проход для расчета порога (на хороших данных)
    kf_init = KalmanFilter2D(q=q, r=r)
    errors = []
    for val in data:
        inv, _ = kf_init.update(val)
        errors.append(abs(inv))
    
    # Считаем порог (возьмем 5 сигм для надежности против ступенек)
    threshold = np.mean(errors) + 5 * np.std(errors)
    
    # 2. Второй проход с использованием подтверждения
    kf = KalmanFilter2DWithPersistence(q=q, r=r, persistence=persistence)
    results = []
    for val in data:
        alarm, filtered, err = kf.update(val, threshold)
        results.append({
            'val': val,
            'kalman_error': err,
            'alarm': alarm
        })
        
    return pd.DataFrame(results), threshold

d=analyze_sensor_final(df,'Температура газов за ТНД максимальная (Расчетная)')
d[0]['alarm'].value_counts()

# n=-1
# for i in d[0]['is_anomaly']:
#     n+=1
#     if i == True:
#         print(n)
#         break
# d[0][4964:5010]

alarm
False    12659
Name: count, dtype: int64

In [29]:
def analyze_ensemble(df, col, slew_factor=3, std_factor=3, k_factor=3, p=3):
    # Очистка данных
    data = df[col].ffill().bfill().values
    train = data[:100]
    
    # Расчет порогов
    s_th = np.median(np.abs(np.diff(train))) * slew_factor 
    std_th = np.std(train) * std_factor
    
    # Калибровка Калмана
    # Передаем: slew, std, kalman_th (пока 1000), window, persistence, q, r
    kf_temp = EnsembleDetector(1000, 1000, 1000, 20, 5, 1e-4, 1e-2)
    k_errors = [kf_temp.update(v)['kalman_err'] for v in train]
    k_th = (np.mean(k_errors) + np.std(k_errors)) * k_factor
    
    # Основной детектор
    detector = EnsembleDetector(
        slew_threshold=s_th, 
        std_threshold=std_th, 
        kalman_threshold=k_th, 
        window_size=20, 
        persistence=p,
        k_q_val=1e-4, 
        k_r_val=1e-2
    )
    
    results = [detector.update(v) for v in data]
    res_df = pd.DataFrame(results)
    return res_df

d=analyze_ensemble(df,'Температура газов за ТНД максимальная (Расчетная)')
d['alarm'].value_counts()
# n=-1
# l=0
# for i in d['alarm']:
#     n+=1
#     if i == True:
#         print(n)
#         l+=1
#         if l == 50:
#             break
# d[4350:4400]

alarm
False    10084
True      2575
Name: count, dtype: int64

In [57]:
difference(df, 'Температура масла в магистрали общей откачки (поз. Тм)')

         diff
0       0.000
1       0.000
2       0.000
3       0.000
4       0.000
...       ...
12654   0.000
12655   0.000
12656   0.000
12657  56.439
12658  20.000

[12659 rows x 1 columns]

In [59]:
accelerate(df, 'Температура масла в магистрали общей откачки (поз. Тм)')

          acc
0       0.000
1       0.000
2       0.000
3       0.000
4       0.000
...       ...
12654   0.000
12655   0.000
12656   0.000
12657  56.439
12658 -36.439

[12659 rows x 1 columns]

In [61]:
add_features(df, 'Температура масла в магистрали общей откачки (поз. Тм)')

,Температура масла в магистрали общей откачки (поз. Тм),Температура слива масла из опоры турбины (поз. Т606),Температура масла на входе в двигатель за фильтром (поз. Т607),Температура топливного газа перед СК (перед расходомерным устройством) (поз. Ттг),Давление масла в нагнетающей магистрали двигателя (после фильтра) (поз. Pм),Давление масла в магистрали общей откачки (поз. Р615),Давление за ОК Pk1,Давление за ОК Pk2,Давление топливного газа перед дозаторами (поз. Pтг1.1),Вибрация промежуточного корпуса газогенератора (гориз.) (поз. В1),...,Температура воздуха на входе в газогенератор (Расчетная),Давление воздуха за компрессором (Расчетная),Частота вращения РНД приведенная,Частота вращения РВД приведенная,Температура газов за ТНД максимальная (Расчетная),Положение лопаток НА КВД. (поз. A2),Положение КПВ (поз. A3),mean,std,slope
0,21.548,28.160,24.361,8.762,302.095,198.239,244.713,257.590,2917.776,1.977,...,5.601,250.959,4119.418,9722.291,439.119,16.139,8.072,0.00000,0.000000,0.000
1,21.548,28.160,24.361,8.762,302.095,198.239,244.713,257.590,2917.776,1.977,...,5.601,251.152,4119.683,9722.339,439.119,16.139,8.072,0.00000,0.000000,0.000
2,21.548,28.160,24.361,8.762,302.559,198.220,243.865,258.663,2916.046,1.972,...,5.601,251.152,4119.905,9722.395,439.119,15.876,7.931,0.00000,0.000000,0.000
3,21.548,28.160,24.361,8.762,302.559,198.220,243.865,258.663,2916.046,1.972,...,5.601,251.264,4119.905,9722.395,439.107,15.876,7.931,0.00000,0.000000,0.000
4,21.548,28.230,24.361,8.762,302.262,197.553,243.865,257.820,2915.057,1.977,...,5.601,251.264,4119.773,9722.260,439.107,15.758,7.931,0.00000,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12654,43.561,65.943,23.177,23.477,308.473,199.926,935.612,941.988,2859.809,3.783,...,4.822,939.183,7834.907,10856.534,586.625,79.420,9.020,43.52254,0.049755,0.000
12655,43.561,65.943,23.107,23.477,308.473,199.926,933.762,942.065,2860.674,3.786,...,4.822,938.800,7837.355,10857.264,586.625,79.667,9.014,43.52300,0.050007,0.000
12656,43.561,65.943,23.107,23.477,308.473,199.926,933.762,942.065,2860.674,3.786,...,4.822,937.913,7837.810,10858.309,586.625,79.667,9.014,43.52346,0.050253,0.000
12657,100.000,65.943,23.107,23.477,308.232,200.667,934.841,942.065,2857.584,3.778,...,4.822,937.913,7838.946,10857.461,586.625,79.637,8.975,44.65270,7.987189,56.439
12658,120.000,65.943,23.107,23.477,307.527,199.277,934.918,939.766,2857.584,3.778,...,4.822,938.453,7838.946,10857.461,586.625,79.692,8.927,46.18194,13.313342,20.000

In [27]:
def clean_sensor_data(series):
    """
    Надежное преобразование колонки в числа.
    """
    # 1. Переводим в строку на случай, если там смешанные типы
    s = series.astype(str)
    
    # 2. Убираем пробелы (бывают невидимые пробелы-разделители тысяч)
    s = s.str.strip().str.replace(r'\s+', '', regex=True)
    
    # 3. Меняем запятую на точку
    s = s.str.replace(',', '.')
    
    # 4. Преобразуем в число
    numeric_data = pd.to_numeric(s, errors='coerce')
    
    # 5. ВАЖНО: Вместо fillna(0) используем ffill() (заполнение предыдущим значением).
    # Если одна строка битая, датчик просто "сохранит" предыдущее значение, 
    # а не прыгнет в ноль (что вызвало бы ложный отказ).
    return numeric_data.ffill().bfill().values


def analyze_robust_sensor(df, column_name, window=20, factor=3.0, max_dur=3, min_th=0.5):
    # Очистка данных (ваша функция)
    data = clean_sensor_data(df[column_name])
    
    detector = RobustStateDetector(
        window_size=window, 
        threshold_factor=factor, 
        max_spike_duration=max_dur,
        min_threshold=min_th
    )
    
    results = []
    for val in data:
        alarm, dev, th = detector.update(float(val))
        results.append({
            'val': val,
            'deviation': dev,
            'threshold': th,
            'alarm': alarm
        })
    
    return pd.DataFrame(results)

d = analyze_robust_sensor(df, 'Температура газов за ТНД максимальная (Расчетная)', window=20, factor=2.5, max_dur=3, min_th=0.3)
d['alarm'].value_counts()
# n=-1
# l=0
# for i in d['alarm']:
#     n+=1
#     if i == True:
#         print(n)
#         l+=1
#         if l == 50:
#             break
# d[950:975]

alarm
False    12511
True       148
Name: count, dtype: int64